### PR TITLE
Added support for token-based authorization (without any dependant pa…

### PR DESCRIPTION
**Pull request by ahusic-clgx**
Added support for token-based authorization (without any dependent packages) and ability to retrieve multiple configuration fragments.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ahusic-clgx Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=SteeltoeOSS/Configuration&pullRequestId=29)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=SteeltoeOSS/Configuration&pullRequestId=29) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ahusic-clgx Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=SteeltoeOSS/Configuration&pullRequestId=29)!

**Comment by dtillman** [comment]
@ahusic-clgx

Have you looked into using the [Pivotal packages](https://www.nuget.org/packages/Pivotal.Extensions.Configuration.ConfigServerCore/) of the config server client.  Those packages already contain OAuth support.  They are compatible with Spring Cloud Services but you should be able to use them in other environments...  If these packages won't work .. let me know.

Also, I believe breaking up configuration into multiple fragments is already supported by config-server by either configuring search paths for the server or by other config-server features.  Can you explore those features and let me know if they won't do what you need?

Dave

**Comment by jkonicki** [comment]
Hello, thank you for creating the PR, but as Dave mentioned we already have this support.  

Closing this now.  Reopen if you have more questions.

Please note: we will be combining the Steeltoe and Pivotal packages mentioned above in our release of 2.2.0.

**Comment by ahusic-clgx** [comment]
Thank you so much for your response Dave and Jason.

I have been using Pivotal's packages (instead of SteelToes) and they are working just fine. OAuth is supported out-of-the-box. Kudos to work done.

However, I would very much like a support for multiple configuration fragment loads for an application. What I was thinking about was extending "Pivotal.Extensions.Configuration.ConfigServer.ConfigServerClientSettings" with new property called "Fragments":

 public class ConfigServerClientSettings
  {
       public Collection<string> Fragments{ get; } = new Collection<string>();
   }

and then use this collection of strings in "ConfigServerConfigurationProvider" class to load each fragment along side application configuration. It would be app's responsibility to provide fragments it needs (besides its own) to successfully work.

 This way, I can load not only app configuration, but any other "shared fragment" application needs.

Thank you very much.

**Pull request closed without merging**
