### PR TITLE
 feature:add netstandard2.0 support

### PR DESCRIPTION
**Pull request by laoshancun**
feature:add netstandard2.0 support  …
Microsoft.Extensions.Configuration.IConfigurationBuilder.Sources on netstandard1.3 is IEnumerable<IConfigurationSource>,and on netstandard2.0 is IList<IConfigurationSource>.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@laoshancun Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=SteeltoeOSS/Configuration&pullRequestId=20)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=SteeltoeOSS/Configuration&pullRequestId=20) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@laoshancun Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=SteeltoeOSS/Configuration&pullRequestId=20)!

**Comment by TimHess** [comment]
Hi @laoshancun 
Thanks for your PR, we appreciate the contribution, but if you have a look at our dev branch we've already got netstandard2.0 supported there. Packages from the dev branch are available in they MyGet feed if you would like to develop with them now https://www.myget.org/gallery/steeltoedev

**Comment by laoshancun** [comment]
ok ,thx

**Pull request closed without merging**
